version: "3.7"
services:

  redis:
    container_name: redis
    image: redis:5.0.14-alpine
    ports:
      - "6379:6379"
    command: redis-server --include /usr/local/etc/redis/redis.conf
    volumes:
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: postgres
    image: "postgres:12-alpine"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

  localstack:
    image: localstack/localstack
    container_name: localstack_service
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
    volumes:
      - ./docker/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.8.1"
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./docker/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
